#!/usr/bin/env bash
# Package built kernel image(s) into a flashable AnyKernel3 zip.
#
# Local usage:
#   DEVICE_NAME=selene KERNEL_VERSION=4.19.325-mykernel ./scripts/package-anykernel.sh
#
# Reads the image manifest written by build-kernel.sh (out/kck-images.txt).
# Kernel images (Image*) go into the zip; dtbo.img / merged dtb are staged
# NEXT TO the zip instead — flashing dtbo/dtb via AnyKernel3 is
# device-specific and can brick (docs/troubleshooting.md).
#
# When ANYKERNEL_REPO is empty, upstream AnyKernel3 is cloned and anykernel.sh
# is generated from this script's template. When ANYKERNEL_REPO points at your
# own AK3 fork, that repo's anykernel.sh is kept untouched.

set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
# shellcheck source=env.sh
. "$SCRIPT_DIR/env.sh"

require_env DEVICE_NAME "e.g. DEVICE_NAME=selene"
cd "$KERNEL_PATH"

AK3_REPO_DEFAULT="https://github.com/osm0sis/AnyKernel3"
AK3_REPO="${ANYKERNEL_REPO:-$AK3_REPO_DEFAULT}"

# Generated anykernel.sh knobs (override via env)
KERNEL_STRING="${KERNEL_STRING:-kernel-ci-kit build for $DEVICE_NAME}"
AK3_BLOCK="${AK3_BLOCK:-auto}"                       # MT6768 fallback: /dev/block/bootdevice/by-name/boot TODO(verify)
AK3_SLOT_DEVICE="${AK3_SLOT_DEVICE:-auto}"           # TODO(verify): hardcode 1/0 if auto misdetects
AK3_DEVICE_NAMES="${AK3_DEVICE_NAMES:-$DEVICE_NAME}" # space separated; first becomes device.name1
AK3_PATCH_VBMETA="${AK3_PATCH_VBMETA:-0}"            # 0 = never patch vbmeta (MediaTek-safe)

# generate_anykernel_sh <dest> — render the AK3 config script.
# Lives before first use so bash has parsed it (functions are not hoisted).
generate_anykernel_sh() {
  local dest="$1" i=1 name
  local -a names=()
  read -r -a names <<< "$AK3_DEVICE_NAMES"
  # properties() block is single-quoted — strip quotes/newlines defensively.
  KERNEL_STRING="$(printf '%s' "$KERNEL_STRING" | tr -d "'\n")"
  {
    cat <<EOF
### AnyKernel3 Ramdisk Mod Script
## generated by kernel-ci-kit (template: scripts/package-anykernel.sh)
### AnyKernel setup
# begin properties
properties() { '
kernel.string=$KERNEL_STRING
do.devicecheck=1
do.modules=0
do.systemless=1
do.cleanup=1
do.cleanuponabort=0
EOF
    for name in "${names[@]}"; do
      printf 'device.name%s=%s\n' "$i" "$name"
      i=$((i + 1))
    done
    cat <<EOF
supported.versions=
supported.patchlevels=
supported.vendorpatchlevels=
'; } # end properties

### AnyKernel install
# begin attributes
boot_attributes() {
set_perm_recursive 0 0 755 644 \$RAMDISK/*;
set_perm_recursive 0 0 750 750 \$RAMDISK/init* \$RAMDISK/sbin;
} # end attributes

## boot shell variables
block=$AK3_BLOCK;
is_slot_device=$AK3_SLOT_DEVICE;
ramdisk_compression=auto;
# Never patch vbmeta on MediaTek — HyperOS/MIUI validates the boot chain
# and a broken vbmeta can hard-brick. See docs/troubleshooting.md.
patch_vbmeta_flag=$AK3_PATCH_VBMETA;

# import functions/variables and setup patching - see for reference (DO NOT REMOVE)
. tools/ak3-core.sh;

## boot install
# unpack boot, replace kernel only, keep stock ramdisk/dtb intact
dump_boot;
write_boot;
## end boot install
EOF
  } > "$dest"
  chmod 0644 "$dest"
}

# ---- inputs ----------------------------------------------------------------
MANIFEST="${MANIFEST:-$OUT_DIR/kck-images.txt}"
[ -f "$MANIFEST" ] || die "image manifest not found: $MANIFEST — run build-kernel.sh first"

if [ -z "${KERNEL_VERSION:-}" ]; then
  KERNEL_VERSION="$(make -s "O=$OUT_DIR" "ARCH=$ARCH" kernelrelease 2>/dev/null | tail -n1 || true)"
  KERNEL_VERSION="${KERNEL_VERSION:-unknown}"
fi

KERNEL_IMAGES=()
EXTRA_IMAGES=()
while IFS= read -r line; do
  [ -n "$line" ] || continue
  [ -f "$line" ] || die "manifest lists missing file: $line"
  base="$(basename -- "$line")"
  case "$base" in
    Image|Image.*|zImage) KERNEL_IMAGES+=("$line") ;;
    *)                    EXTRA_IMAGES+=("$line") ;;
  esac
done < "$MANIFEST"

[ "${#KERNEL_IMAGES[@]}" -gt 0 ] || die "manifest has no kernel image (Image*) — nothing to package"

# ---- safety: never let bootchain blobs near the zip ------------------------
# TODO(verify): extend the blocklist if your device has extra critical parts.
for line in "${KERNEL_IMAGES[@]}" "${EXTRA_IMAGES[@]+"${EXTRA_IMAGES[@]}"}"; do
  [ -n "$line" ] || continue
  base="$(basename -- "$line")"
  case "$base" in
    lk|lk_a.img|lk_b.img|preloader*|vbmeta*|tee*|scp*|sspm*|tz.img|spmfw*|md1img*|sgpt*|expdb*)
      die "REFUSING to package bootchain partition '$base' — flashing these bricks devices"
      ;;
  esac
done
for line in "${EXTRA_IMAGES[@]+"${EXTRA_IMAGES[@]}"}"; do
  if [ -n "$line" ]; then
    warn "staging outside zip (not flashed by AK3): $line"
  fi
done

# ---- zip name --------------------------------------------------------------
DATE_STAMP="$(date -u +%Y%m%d)"
SAFE_DEVICE="$(printf '%s' "$DEVICE_NAME" | tr -c 'A-Za-z0-9._-' '-' | sed 's/-\{1,\}$//')"
SAFE_VERSION="$(printf '%s' "$KERNEL_VERSION" | tr ' /' '--')"
ZIP_NAME="$(printf '%s' "$ZIP_NAME_TEMPLATE" \
  | sed "s/{device}/$SAFE_DEVICE/g; s/{version}/$SAFE_VERSION/g; s/{date}/$DATE_STAMP/g")"
case "$ZIP_NAME" in
  *.zip) ;;
  *) ZIP_NAME="$ZIP_NAME.zip" ;;
esac

DIST_DIR="${DIST_DIR:-dist}"
mkdir -p "$DIST_DIR"
DIST_ABS="$(CDPATH='' cd -- "$DIST_DIR" && pwd)"
ZIP_PATH="$DIST_ABS/$ZIP_NAME"

# ---- assemble --------------------------------------------------------------
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
AK3="$TMP/ak3"

log "cloning AnyKernel3: $AK3_REPO (branch: $ANYKERNEL_BRANCH)"
git clone --depth 1 --branch "$ANYKERNEL_BRANCH" "$AK3_REPO" "$AK3" \
  || die "failed to clone $AK3_REPO (check anykernel_repo / anykernel_branch)"
rm -rf "$AK3/.git"

if [ -n "${ANYKERNEL_REPO:-}" ]; then
  log "using fork-supplied anykernel.sh: $ANYKERNEL_REPO"
else
  log "generating anykernel.sh (device: $DEVICE_NAME)"
  generate_anykernel_sh "$AK3/anykernel.sh"
fi

for img in "${KERNEL_IMAGES[@]}"; do
  cp "$img" "$AK3/"
  log "staged: $img"
done

# Post-assembly blocklist scan (defense in depth, incl. fork contents).
# Note: Image.gz-dtb ends in "-dtb", not ".dtb" — it is NOT matched.
FOUND_SENSITIVE="$(find "$AK3" -maxdepth 1 \( -iname 'lk' -o -iname 'lk_*.img' \
  -o -iname 'preloader*' -o -iname 'vbmeta*' -o -iname 'dtbo.img' \
  -o -iname '*.dtb' -o -iname 'tee*' \) -print || true)"
if [ -n "$FOUND_SENSITIVE" ]; then
  printf '%s\n' "$FOUND_SENSITIVE" | sed 's/^/    /' >&2
  die "sensitive file(s) found in AnyKernel3 tree — refusing to zip (brick risk)"
fi

rm -f "$ZIP_PATH"
log "zipping: $ZIP_PATH"
if ! ( cd "$AK3" && zip -r9 "$ZIP_PATH" . -x '*.git*' -x '*.md' ) > "$TMP/zip.log" 2>&1; then
  cat "$TMP/zip.log" >&2
  die "zip failed"
fi

SHA="$(sha256_file "$ZIP_PATH")"
printf '%s  %s\n' "$SHA" "$ZIP_NAME" > "$ZIP_PATH.sha256"
log "zip:     $ZIP_PATH ($(du -h "$ZIP_PATH" | awk '{print $1}'))"
log "sha256:  $SHA"

for extra in "${EXTRA_IMAGES[@]+"${EXTRA_IMAGES[@]}"}"; do
  [ -n "$extra" ] || continue
  cp "$extra" "$DIST_DIR/"
  log "staged next to zip: $DIST_DIR/$(basename -- "$extra")"
done

gh_output zip_path "$ZIP_PATH"
gh_output zip_name "$ZIP_NAME"
gh_output zip_sha256 "$SHA"
gh_output kernel_version "$KERNEL_VERSION"

log "package done"
