#!/usr/bin/env bash
# Package built kernel image(s) into a flashable AnyKernel3 zip.
#
# Local usage:
#   DEVICE_NAME=selene KERNEL_VERSION=4.19.325-mykernel ./scripts/package-anykernel.sh
#
# Reads the image manifest written by build-kernel.sh (out/kck-images.txt).
# Exactly ONE kernel image (the preferred one, normally Image.gz-dtb) goes into
# the zip — AnyKernel3 flashes a single image and picks it by its own fixed
# priority list, so shipping extras makes it choose the wrong format.
# dtbo.img / merged dtb are staged NEXT TO the zip instead — flashing
# dtbo/dtb via AnyKernel3 is device-specific and can brick
# (docs/troubleshooting.md).
#
# When ANYKERNEL_REPO is empty, upstream AnyKernel3 is cloned and anykernel.sh
# is generated from this script's template. When ANYKERNEL_REPO points at your
# own AK3 fork, that repo's anykernel.sh is kept untouched.

set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
# shellcheck source=env.sh
. "$SCRIPT_DIR/env.sh"

require_env DEVICE_NAME "e.g. DEVICE_NAME=selene"
cd "$KERNEL_PATH"

AK3_REPO_DEFAULT="https://github.com/osm0sis/AnyKernel3"
AK3_REPO="${ANYKERNEL_REPO:-$AK3_REPO_DEFAULT}"

# Generated anykernel.sh knobs (override via env)
KERNEL_STRING="${KERNEL_STRING:-kernel-ci-kit build for $DEVICE_NAME}"
AK3_BLOCK="${AK3_BLOCK:-auto}"                       # MT6768 fallback: /dev/block/bootdevice/by-name/boot TODO(verify)
AK3_SLOT_DEVICE="${AK3_SLOT_DEVICE:-auto}"           # TODO(verify): hardcode 1/0 if auto misdetects
AK3_DEVICE_NAMES="${AK3_DEVICE_NAMES:-$DEVICE_NAME}" # space separated; first becomes device.name1
AK3_PATCH_VBMETA="${AK3_PATCH_VBMETA:-0}"            # 0 = never patch vbmeta (MediaTek-safe)

# generate_anykernel_sh <dest> — render the AK3 config script.
# Lives before first use so bash has parsed it (functions are not hoisted).
generate_anykernel_sh() {
  local dest="$1" i=1 name
  local -a names=()
  read -r -a names <<< "$AK3_DEVICE_NAMES"
  # properties() block is single-quoted — strip quotes/newlines defensively.
  KERNEL_STRING="$(printf '%s' "$KERNEL_STRING" | tr -d "'\n")"
  {
    cat <<EOF
### AnyKernel3 Ramdisk Mod Script
## generated by kernel-ci-kit (template: scripts/package-anykernel.sh)
### AnyKernel setup
# begin properties
properties() { '
kernel.string=$KERNEL_STRING
do.devicecheck=1
do.modules=0
do.systemless=1
do.cleanup=1
do.cleanuponabort=0
EOF
    for name in "${names[@]}"; do
      printf 'device.name%s=%s\n' "$i" "$name"
      i=$((i + 1))
    done
    cat <<EOF
supported.versions=
supported.patchlevels=
supported.vendorpatchlevels=
'; } # end properties

### AnyKernel install
# begin attributes
boot_attributes() {
set_perm_recursive 0 0 755 644 \$RAMDISK/*;
set_perm_recursive 0 0 750 750 \$RAMDISK/init* \$RAMDISK/sbin;
} # end attributes

## boot shell variables
BLOCK=$AK3_BLOCK;
IS_SLOT_DEVICE=$AK3_SLOT_DEVICE;
RAMDISK_COMPRESSION=auto;
# Never patch vbmeta on MediaTek — HyperOS/MIUI validates the boot chain
# and a broken vbmeta can hard-brick. See docs/troubleshooting.md.
PATCH_VBMETA_FLAG=$AK3_PATCH_VBMETA;

# import functions/variables and setup patching - see for reference (DO NOT REMOVE)
. tools/ak3-core.sh;

## boot install
# unpack boot, replace kernel only, keep stock ramdisk/dtb intact
dump_boot;
write_boot;
## end boot install
EOF
  } > "$dest"
  chmod 0644 "$dest"
}

# ---- inputs ----------------------------------------------------------------
MANIFEST="${MANIFEST:-$OUT_DIR/kck-images.txt}"
[ -f "$MANIFEST" ] || die "image manifest not found: $MANIFEST — run build-kernel.sh first"

if [ -z "${KERNEL_VERSION:-}" ]; then
  KERNEL_VERSION="$(make -s "O=$OUT_DIR" "ARCH=$ARCH" kernelrelease 2>/dev/null | tail -n1 || true)"
  KERNEL_VERSION="${KERNEL_VERSION:-unknown}"
fi

KERNEL_IMAGES=()
EXTRA_IMAGES=()
while IFS= read -r line; do
  [ -n "$line" ] || continue
  [ -f "$line" ] || die "manifest lists missing file: $line"
  base="$(basename -- "$line")"
  case "$base" in
    Image|Image.*|zImage) KERNEL_IMAGES+=("$line") ;;
    *)                    EXTRA_IMAGES+=("$line") ;;
  esac
done < "$MANIFEST"

[ "${#KERNEL_IMAGES[@]}" -gt 0 ] || die "manifest has no kernel image (Image*) — nothing to package"

# AnyKernel3 flashes exactly one kernel image, and picks it by its own fixed
# priority list (tools/ak3-core.sh: "zImage ... Image Image.gz Image.gz-dtb ...").
# Shipping more than one makes AK3 pick the wrong one — e.g. a raw Image (30 MB)
# beats Image.gz-dtb there and is not what the boot image expects. So pick one
# image ourselves, preferring the compressed+dtb variants.
PRIMARY_IMAGE=""
for cand in Image.gz-dtb Image.gz Image-dtb Image zImage-dtb zImage; do
  for img in "${KERNEL_IMAGES[@]}"; do
    if [ "$(basename -- "$img")" = "$cand" ]; then
      PRIMARY_IMAGE="$img"
      break 2
    fi
  done
done
if [ -z "$PRIMARY_IMAGE" ]; then
  PRIMARY_IMAGE="${KERNEL_IMAGES[0]}"
fi
log "primary image: $(basename -- "$PRIMARY_IMAGE")"

SKIPPED_IMAGES=()
for img in "${KERNEL_IMAGES[@]}"; do
  if [ "$img" != "$PRIMARY_IMAGE" ]; then
    SKIPPED_IMAGES+=("$(basename -- "$img")")
  fi
done
if [ "${#SKIPPED_IMAGES[@]}" -gt 0 ]; then
  log "not packaged (AK3 flashes exactly one image): ${SKIPPED_IMAGES[*]}"
fi

# ---- safety: never let bootchain blobs near the zip ------------------------
# TODO(verify): extend the blocklist if your device has extra critical parts.
for line in "${KERNEL_IMAGES[@]}" "${EXTRA_IMAGES[@]+"${EXTRA_IMAGES[@]}"}"; do
  [ -n "$line" ] || continue
  base="$(basename -- "$line")"
  case "$base" in
    lk|lk_a.img|lk_b.img|preloader*|vbmeta*|tee*|scp*|sspm*|tz.img|spmfw*|md1img*|sgpt*|expdb*)
      die "REFUSING to package bootchain partition '$base' — flashing these bricks devices"
      ;;
  esac
done
for line in "${EXTRA_IMAGES[@]+"${EXTRA_IMAGES[@]}"}"; do
  if [ -n "$line" ]; then
    warn "staging outside zip (not flashed by AK3): $line"
  fi
done

# ---- zip name --------------------------------------------------------------
DATE_STAMP="$(date -u +%Y%m%d)"
SAFE_DEVICE="$(printf '%s' "$DEVICE_NAME" | tr -c 'A-Za-z0-9._-' '-' | sed 's/-\{1,\}$//')"
SAFE_VERSION="$(printf '%s' "$KERNEL_VERSION" | tr ' /' '--')"
SAFE_TOOLCHAIN="$(printf '%s' "${TOOLCHAIN:-stock}" | tr -c 'A-Za-z0-9._-' '-' | sed 's/-\{1,\}$//')"
ZIP_NAME="$(printf '%s' "$ZIP_NAME_TEMPLATE" \
  | sed "s/{device}/$SAFE_DEVICE/g; s/{version}/$SAFE_VERSION/g; s/{toolchain}/$SAFE_TOOLCHAIN/g; s/{date}/$DATE_STAMP/g")"
case "$ZIP_NAME" in
  *.zip) ;;
  *) ZIP_NAME="$ZIP_NAME.zip" ;;
esac

DIST_DIR="${DIST_DIR:-dist}"
mkdir -p "$DIST_DIR"
DIST_ABS="$(CDPATH='' cd -- "$DIST_DIR" && pwd)"
ZIP_PATH="$DIST_ABS/$ZIP_NAME"

# ---- assemble --------------------------------------------------------------
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
AK3="$TMP/ak3"

log "cloning AnyKernel3: $AK3_REPO (ref: $ANYKERNEL_BRANCH)"
# `--branch` only takes a branch/tag; a commit SHA needs a full clone + checkout.
if ! git clone --quiet --depth 1 --branch "$ANYKERNEL_BRANCH" "$AK3_REPO" "$AK3" 2>/dev/null; then
  rm -rf "$AK3"
  if ! git clone --quiet "$AK3_REPO" "$AK3" || ! git -C "$AK3" checkout --quiet "$ANYKERNEL_BRANCH"; then
    die "failed to clone $AK3_REPO at $ANYKERNEL_BRANCH (check anykernel_repo / anykernel_branch)"
  fi
fi
rm -rf "$AK3/.git"

# A device-supplied config wins over the generated template — it carries the
# device aliases and branding the device tree has always shipped with.
# KERNEL_PATH is relative (CI passes `kernel`), and we already cd'd into it,
# so resolve against $PWD — not against $KERNEL_PATH a second time.
DEVICE_ANYKERNEL="$PWD/scripts/anykernel.sh"
if [ -n "${ANYKERNEL_REPO:-}" ]; then
  log "using fork-supplied anykernel.sh: $ANYKERNEL_REPO"
elif [ -f "$DEVICE_ANYKERNEL" ]; then
  log "using device anykernel.sh: $DEVICE_ANYKERNEL"
  cp "$DEVICE_ANYKERNEL" "$AK3/anykernel.sh"
else
  log "generating anykernel.sh (device: $DEVICE_NAME)"
  generate_anykernel_sh "$AK3/anykernel.sh"
fi

# Guard: AK3 cea8f97 (2026-06-28) dropped the lowercase block=/is_slot_device=
# aliases, so such a config leaves $BLOCK empty and the flash aborts with
# "Unable to determine partition" — fail here, not after a 16 minute build.
# shellcheck disable=SC2016  # literal '$block' is the AK3 code we grep for
if grep -qE '^[[:space:]]*block=' "$AK3/anykernel.sh" \
   && ! grep -q 'BLOCK="$block"' "$AK3/tools/ak3-core.sh"; then
  die "anykernel.sh uses lowercase block= but AnyKernel3 @ $ANYKERNEL_BRANCH no longer maps it (cea8f97) — keep anykernel_branch=dca9dc3 or convert the config to BLOCK=/IS_SLOT_DEVICE="
fi

cp "$PRIMARY_IMAGE" "$AK3/"
log "staged: $PRIMARY_IMAGE"

# Post-assembly safety: AK3 must see exactly one kernel image, otherwise it
# picks by its own priority order and can flash a format the boot image lacks.
IMAGE_COUNT=0
for f in "$AK3"/Image "$AK3"/zImage "$AK3"/Image.* "$AK3"/zImage.*; do
  if [ -f "$f" ]; then
    IMAGE_COUNT=$((IMAGE_COUNT + 1))
    [ "$IMAGE_COUNT" -le 1 ] || die "AK3 tree holds multiple kernel images — flashing the wrong one risks a bootloop"
  fi
done
[ "$IMAGE_COUNT" -eq 1 ] || die "AK3 tree has no kernel image — nothing to flash"

# Post-assembly blocklist scan (defense in depth, incl. fork contents).
# Note: Image.gz-dtb ends in "-dtb", not ".dtb" — it is NOT matched.
FOUND_SENSITIVE="$(find "$AK3" -maxdepth 1 \( -iname 'lk' -o -iname 'lk_*.img' \
  -o -iname 'preloader*' -o -iname 'vbmeta*' -o -iname 'dtbo.img' \
  -o -iname '*.dtb' -o -iname 'tee*' \) -print || true)"
if [ -n "$FOUND_SENSITIVE" ]; then
  printf '%s\n' "$FOUND_SENSITIVE" | sed 's/^/    /' >&2
  die "sensitive file(s) found in AnyKernel3 tree — refusing to zip (brick risk)"
fi

rm -f "$ZIP_PATH"
log "zipping: $ZIP_PATH"
if ! ( cd "$AK3" && zip -r9 "$ZIP_PATH" . -x '*.git*' -x '*.md' ) > "$TMP/zip.log" 2>&1; then
  cat "$TMP/zip.log" >&2
  die "zip failed"
fi

SHA="$(sha256_file "$ZIP_PATH")"
printf '%s  %s\n' "$SHA" "$ZIP_NAME" > "$ZIP_PATH.sha256"
log "zip:     $ZIP_PATH ($(du -h "$ZIP_PATH" | awk '{print $1}'))"
log "sha256:  $SHA"

for extra in "${EXTRA_IMAGES[@]+"${EXTRA_IMAGES[@]}"}"; do
  [ -n "$extra" ] || continue
  cp "$extra" "$DIST_DIR/"
  log "staged next to zip: $DIST_DIR/$(basename -- "$extra")"
done

gh_output zip_path "$ZIP_PATH"
gh_output zip_name "$ZIP_NAME"
gh_output zip_sha256 "$SHA"
gh_output kernel_version "$KERNEL_VERSION"

log "package done"
